### ISSUE TITLE
recyclerView扩展的divider，当使用宫格展示时，纵向分割线失效

### ISSUE THREAD

**Issue by vihuela** [li-xiaojun/AndroidKTX#10]

**Comment by li-xiaojun** [comment]
@vihuela 我这边测试是没问题，给个代码和效果截图

**Comment by vihuela** [comment]
@li-xiaojun 
![image](https://user-images.githubusercontent.com/6533060/59829374-de324480-936f-11e9-947d-36e1345f6d70.png)

**Comment by PiterPeng** [comment]
> @li-xiaojun
> ![image](https://user-images.githubusercontent.com/6533060/59829374-de324480-936f-11e9-947d-36e1345f6d70.png)

这几张图不错，能不能分享一下做个Demo

**Comment by vihuela** [comment]
@PiterPeng 来来来，。这个https://github.com/vihuela/Kotlin-mvpro
