### ISSUE TITLE
可以更新到OKhttp4 么

### ISSUE THREAD

**Issue by akvsdk** [li-xiaojun/AndroidKTX#12]
[OkHttp Upgrading to OkHttp 4](https://square.github.io/okhttp/upgrading_to_okhttp_4/)

**Comment by li-xiaojun** [comment]
目前必要性不大，ok4只是用kotlin重新，没有性能提升和API改进。升级还可能需要修改一些额外的配置，所以暂不升级。

**Comment by akvsdk** [comment]
OK
