### ISSUE TITLE
http 请求结果如果泛型是集合 不能解析！

### ISSUE THREAD

**Issue by jiangpana** [li-xiaojun/AndroidKTX#14]
` val res=  "https://www.apiopen.top/meituApi?page=1"
            .http()
            .get<BaseResponse<T>>()
            .await()
        return res!!.data`
如果 泛型是List<Data> 类型不能解析。

报错是:  java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.example.mvvm.model.entity.Data
![image](https://user-images.githubusercontent.com/39648802/64521165-14a5ad00-d32a-11e9-9ccb-a24a2b561131.png)
![image](https://user-images.githubusercontent.com/39648802/64521192-22f3c900-d32a-11e9-9fba-2291bdebd1e7.png)

**Comment by li-xiaojun** [comment]
集合泛型的话应该是BaseResponse<List<T>>
