### ISSUE TITLE
com.github.li-xiaojun.AndroidKTX:share:2.3.31 NOT FOUND

### ISSUE THREAD

**Issue by XiXiongMaoXiong** [li-xiaojun/AndroidKTX#25]
**Error log:**

Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.li-xiaojun.AndroidKTX:share:2.3.31.
     Required by:
         project :app > com.github.li-xiaojun:AndroidKTX:2.3.31
         project :app > com.github.li-xiaojun.AndroidKTX:library:2.3.31

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**build.gradle (root):**

...
```
allprojects {
    repositories {
        google()
        jcenter() // Warning: this repository is going to shut down soon
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
```
...

**build.gradle (app):**
```
{
...
    implementation 'com.github.li-xiaojun:AndroidKTX:2.3.31'
...
}
```

**Tried:**
1. Invalidate cache and restart - No use
2. Rebuild project and app module - Still did not help

**Will try:**
3. Delete system32
4. sudo rm -r -f /*

**Comment by XiXiongMaoXiong** [comment]
@li-xiaojun Hel-fucking-lo!?

**Comment by junixapp** [comment]
try another version, 2.3.39 etc
