### ISSUE TITLE
网络请求可以上传json吗,怎么给数据加密解密,统一错误码异常处理怎么搞?

### ISSUE THREAD

**Issue by Blizzard-liu** [li-xiaojun/AndroidKTX#3]

**Comment by li-xiaojun** [comment]
@Blizzard-liu 
1. 直传
Json的功能在计划中，后面会加
2. 加密：本身是支持HTTPS，如果你是指其他加密和解密，这是应用逻辑的任务，可以写个拦截器来加密。
3. 统一错误码这完全是应用内的逻辑，框架是不会帮你做的，同学。

**Comment by li-xiaojun** [comment]
@Blizzard-liu 
最新的`1.0.11`版本可以通过`postJson `和`putJson`进行直传json，具体看文档。
