### ISSUE TITLE
协程问题

### ISSUE THREAD

**Issue by KiWiLss** [li-xiaojun/AndroidKTX#4]
这里面集入了协程吗?用Anko 的方法不能用

**Comment by li-xiaojun** [comment]
@KiWiLss 
目前没有集成Coroutine，可以自己添加。Http的相关扩展可配合Coroutine使用，具体看示例。

**Comment by KiWiLss** [comment]
异步获取后只能这样切换吗,

val job = GlobalScope.launch {
                //Coroutine context is inherited from a [CoroutineScope], additional context elements can be specified with [context] argument.
                val await = "http://guolin.tech/api/china".http().get<List<Province>>().await()
                runOnUiThread {
                    tv_ket_net.text = await!![0].name
                }
            }

**Comment by KiWiLss** [comment]
想用这个用不了
//             doAsync {
//                 val get = "http://guolin.tech/api/china".http().get<List<Province>>()
//                 uiThread {
//
//                 }
//             }

**Comment by KiWiLss** [comment]
找到一种写法,不知道有没有问题.
  runBlocking {
                val job = async {
                    return@async "http://guolin.tech/api/china".http().get<List<Province>>().await()
                }
                job.await()!![0].name.e()
                tv_ket_net.text = job.await()!![0].name
            }

**Comment by KiWiLss** [comment]
已解决

**Comment by li-xiaojun** [comment]
@KiWiLss 
Coroutine内的异步操作可以通过很多方式通知UI，比如：EventBus或者LiveData。一般来说不需要Coroutine间的切换，也不会在UI中直接使用Coroutine。其实anko的Coroutine的封装也基本上没有用武之地，如果你们需要在UI中使用Coroutine，我怀疑你们的架构设计有问题。

**Comment by KiWiLss** [comment]
先通过下面这种方式请求,再用EventBus或者LiveData刷新 UI 界面是否可行呢?
   GlobalScope.launch {
            val response = OkWrapper.okHttpClient
                .newCall(Request.Builder().url("https://baidu.com").get().build())
                .execute()
            val result = response.body()!!.string()
        }
