### ISSUE TITLE
Http日志,LiveDataBus

### ISSUE THREAD

**Issue by KiWiLss** [li-xiaojun/AndroidKTX#6]
1. Http日志怎么开启?
2. LiveDataBus,发送消息,set 和 post 的区别? 有可以发送消息后, 上个 Activity 可以立即接收到的方法吗

**Comment by li-xiaojun** [comment]
@KiWiLss 
Http日志默认就是开启的；
set用户UI线程，post用于异步线程；
发送消息后上个Activity会立即收到消息。

**Comment by KiWiLss** [comment]
1.找到原因了,魅族手机日志默认不显示.
2.observe方法返回上个 Activity 才会收到消息. observeForever可以立即接收到.
3. 日志打印可以打印出在哪个位置并点击跳转到对应的位置吗?

**Comment by li-xiaojun** [comment]
@KiWiLss 
日志打印就是系统的Log方法，它支持的都支持。
