### ISSUE TITLE
协程的使用

### ISSUE THREAD

**Issue by KiWiLss** [li-xiaojun/AndroidKTX#7]
请教一下 
1.像这样直接使用是否会有问题?
GlobalScope.launch {
val response = OkWrapper.okHttpClient
.newCall(Request.Builder().url(“https://baidu.com").get().build())
.execute()
val result = response.body()!!.string()
//使用 EventBus 或 LiveDataBus 通知 UI更新
}
2.对于 Anko 库的协程直接使用是否有什么问题?
doAsync {
Log.e(“MMM”, “: doAsync start” );
val response = OkWrapper.okHttpClient
.newCall(Request.Builder().url(“https://www.baidu.com").get().build())
.execute()
val result = response.body()!!.string()
uiThread {
tv_anko_text.text = “hello world$result”
}
}

**Comment by li-xiaojun** [comment]
第一种方式，是最原始的使用方式，如果这样做就无需使用我这个框架；
第二种请求逻辑和操作UI混合，在架构设计是禁止这样的，后期很难维护，逻辑层和UI层的通信是靠LiveData来完成。

**Comment by KiWiLss** [comment]
1. GlobalScope.launch {
     }
这样直接用没有问题吗,需要取消吗
2.Anko里的异步大概并不会用
3.大佬有没有想过用 Retrofit 配合使用?

**Comment by li-xiaojun** [comment]
1.  GlobalScope.launch { } 的用法默认不会取消，如果想自动取消协程，请参考我的文章：https://juejin.im/post/5ceb3d6ef265da1bb47d4180
2. Anko的异步写法在真实项目基本没有用武之地，所以我不用Anko
3. 我对Okhttp的封装已经是目前最简洁的方案，如果你喜欢Retrofit也可以用它，两者结合没必要啊。
